### ISSUE TITLE
Warn or document backing up nvram settings before flashing upgrades

### ISSUE THREAD

**Issue by deviantintegral** [electrolama/docs#30]
I learned that when flashing with cc2538-bsl.py, that the NVRAM in a zzh! is erased. As this contains important settings like the ZigBee network key, it's pretty easy to end up with a firmware upgrade that requires re-pairing all your devices. In my case, I was lucky, and I had debugging logs from a month ago that included the network key and could recreate the configuration.

As is, there's no mention of backing up nvram at https://electrolama.com/radio-docs/flash-cc-bsl/. zigpy-znp does at https://github.com/zigpy/zigpy-znp/blob/dev/TOOLS.md#backup-and-restore, and I think something similar should be mentioned in these docs. However, I don't see any way to actually do this with cc2538-bsl, making it a little hard to write docs other than a warning. I'm happy to do that if that's as far as we can go.

Any suggestions? I ended up using both tools, as zigpy-znp can't handle `.hex`. If there's a single tool that can manage nvram and do flashing I think we should link to it.

I've never used SmartRF, but at a first read I don't see anything about the possibility of wiping network keys at https://electrolama.com/radio-docs/flash-ti-flash-prog/ or how to back up nvram before upgrading. There may be other places in the docs a warning may be appropriate.

**Comment by omerk** [comment]
Hi @deviantintegral, apologies for the super delayed reply and thanks for the nudge to update documentation about this.

AFAIK there isn't a single tool to deal with all this, partially why I forked cc2538-bsl [here](/electrolama/llama-bsl). Adding NVRAM backup/restore to llama-bsl probably makes sense, although I am not sure when I'll get around to finding the time to adding that in there, help welcome and I'd be happy to send anyone who contributes good bits of functionality some @electrolama hardware as a thank you :-)

In the meantime, I'll add warnings as you've suggested.

**Comment by omerk** [comment]
Warnings added in https://github.com/electrolama/docs/pull/31

Closing this issue
